### ISSUE TITLE
Retrieve all posts liked by a user

### ISSUE THREAD

**Issue by nikitabuida** [bdelespierre/laravel-like-demo#1]
Hi, thank you for the nice tutorial!

It is not clear to me how do I get all posts liked by a user?

I can get all the likes with corresponding likeable type

`
$likes = $user->likes()->where('likeable_type', 'App\Post')->with('likeable')->get();

$likedIdeas = $likes->map(fn ($like) => $like->likeable);
`

But I'd like to have a collection of App\Post models which were liked by a user. Is there an elegant-laravel-way other than iterating through likes collection?

**Comment by bdelespierre** [comment]
Hi @nikitabuida, thanks for submitting an issue.

To retrieve all the posts liked by an user you can simply do:
```php
$user = User::find($id); // << the user who liked the posts you're searching
$posts = Post::whereHas('likes', fn ($q1) => $q1->whereHas('user', fn ($q2) => $q2->whereId($user->id)))->get();
```

See [Laravel Documentation](https://laravel.com/docs/8.x/eloquent-relationships#querying-relationship-existence) for more information about whereHas.

**Comment by bdelespierre** [comment]
Same thing but with regular closures instead of arrow function (easier to read IMHO):

```php
$posts = Post::whereHas('likes', function ($q1) use ($user) {
    $q1->whereHas('user', function ($q2) use ($user) {
        $q2->whereId($user->id);
    });
})->get();
```
